spring:
  mail:
    host: smtp.gmail.com
    username: mailforworkall@gmail.com
    password: *
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
mail:
  debug: true