spring:
  datasource:
    url: jdbc:mysql://192.168.1.111:3306/gel?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: 2006@Nastya


  liquibase:
     change-log: classpath:liquibase/db.changelog-master.xml
     url: jdbc:mysql://192.168.1.111:3306/gel?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
     user: user
     password: 2006@Nastya

